CREATE TABLE memlist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  state TEXT NOT NULL,
  type ENUM NOT NULL,
  packed_size INTEGER NOT NULL,
  size INTEGER NOT NULL,
  rank_num INTEGER NOT NULL,
  bank_id INTEGER NOT NULL,
  bank_offset INTEGER NOT NULL
);
